### ISSUE TITLE
start-searchjob returns 400 Job creation fail

### ISSUE THREAD

**Issue by rickjuryxero** [SumoLogic/sumo-powershell-sdk#18]
I've tried to execute start-searchjob vs the us2 endpoint on both windows and powershell core on MacOS after importing the latest module.

On both platforms the command fails with error similar to below. We have tried various searches and ranges including the one in the get-command example as per below.

```
Start-SearchJob -Query "_sourceCategory=service ERROR" -Last "00:30:00"
Invoke-RestMethod : {
  "status" : 400,
  "id" : "TOE4F-6GCVM-IH9QX",
  "code" : "request.body.missing",
  "message" : "Must provide body with the request."
}
At /usr/local/share/powershell/Modules/SumoLogic-Core/1.1.1/Lib/Utils.ps1:83 char:7
+       & $cmdlet -Uri $url -Headers $headers -Method $method -WebSessi ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: POST, R...ication/json
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
invokeSumoAPI : System.Management.Automation.CmdletInvocationException: {
  "status" : 400,
  "id" : "TOE4F-6GCVM-IH9QX",
  "code" : "request.body.missing",
  "message" : "Must provide body with the request."
} ---> Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 400 (Bad Request).
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
At /usr/local/share/powershell/Modules/SumoLogic-Core/1.1.1/Lib/Utils.ps1:105 char:5
+     invokeSumoAPI $session $headers $method $function $query $body (G ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,invokeSumoAPI

Job creation fail
At /usr/local/share/powershell/Modules/SumoLogic-Core/1.1.1/SearchJob/Start-SearchJob.ps1:79 char:9
+         throw "Job creation fail"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Job creation fail:String) [], RuntimeException
    + FullyQualifiedErrorId : Job creation fail
```

**Comment by rickjuryxero** [comment]
I suspect this line should specify -body not -query https://github.com/SumoLogic/sumo-powershell-sdk/blob/master/src/main/SumoLogic-Core/Lib/Utils.ps1#L143

**Comment by rickjuryxero** [comment]
I think there are actually two issues.
1. it's query not body
2. you have to post JSON not a hash table as $q

by changing it to this I can run queries.
```
function startSearchJob ([SumoAPISession]$session, [string]$query, [datetime]$from, [datetime]$to, [string]$timeZone) {
  $fromT = getUnixTimeStamp ($from)
  $toT = getUnixTimeStamp ($to)
  $q = @{
    "query"    = $query
    "from"     = $fromT
    "to"       = $toT
    "timeZone" = $timeZone
  }

  # POST requirest a JSON payload in body
  $q=$q | ConvertTo-Json 
  Write-Verbose "search/jobs $q"

  invokeSumoRestMethod -session $session -method Post -function "search/jobs" -body $q
}
```

**Comment by rickjuryxero** [comment]
@bin3377 do you want me to do a PR to fix this or is there ETA on sumologic fixing it. start-searchjob commandlet is 100% broken right now.

**Comment by bin3377** [comment]
Thanks for reporting this issue! will take a look ASAP

**Comment by bin3377** [comment]
should be fixed. please check with version 1.1.2

**Comment by rickjuryxero** [comment]
great thanks I can run search jobs again now.
